version: '3.7'

services:
  squid:
    build: squid/
    image: squid-reverse-mf
    env_file: gwproxy.env
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    restart: always

  gw-icap:
    build: c-icap/
    image: gw-icap
    ports:
      - "1344:1344"
    network_mode: host
    restart: always
